accounts/accounts/accounts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('pass/', include('pass.urls')),
]

accounts/accounts/pass/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views 
# from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('reset_password/',auth_views.PasswordResetView.as_view(),name="reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),

    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    
]

accounts/accounts/user/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views

from user.views import city,home,booking,room_details,hotel_list

app_name='user'

urlpatterns = [
    path('register', views.register, name="register"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),
    
    
    ###################user ruls views
    path('', views.index, name="index"),
    path('explore', views.explore, name="explore"),
    path('u_home', views.home, name="u_home"),
    path('hotel_login', views.hotel, name="hotel_login"),
    path('hotel_signup', views.hotel_signup, name="hotel_signup"),
    path('hoteladmin', views.HotelAdmin, name="hoteladmin"),


    path('hotel_list', hotel_list.as_view(), name="hotel_list"),
    path('city', city.as_view(), name="city"),
    path('room-details', room_details.as_view(), name="room-details"),
    path('room_management', views.room_mag, name="room_management"),
    path('booking', booking.as_view(), name="booking"),
    path('data', views.data, name="data"),

    

]


'''
1 - Submit email form                         //PasswordResetView.as_view()
2 - Email sent success message                //PasswordResetDoneView.as_view()
3 - Link to password Rest form in email       //PasswordResetConfirmView.as_view()
4 - Password successfully changed message     //PasswordResetCompleteView.as_view()
'''

accounts/accounts/pass/models.py
from django.db import models

# Create your models here.

accounts/accounts/user/models.py
from django.db import models

# Create your models here.

accounts/accounts/pass/views.py
from django.shortcuts import render

# Create your views here.

accounts/accounts/user/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User, auth
from django.views.generic.list import View
# Create your views here.
 
def register(request):
    if request.method == 'POST':
        F_name = request.POST['fname']
        L_name = request.POST['lname']
        email = request.POST['email']
        password = request.POST['pass']
        password1 = request.POST['cpass']

        if password==password1:
            if User.objects.filter(username=email).exists():
                print('username taken')
                messages.info(request,'E-mail Id already using')
                return redirect('register')
            else:    
                user = User.objects.create_user(username=email, password=password, email=email,first_name=F_name, last_name=L_name)
                user.save()
                print('user created')
                return redirect('login')
        else:
            print('password not matching')
            messages.info(request,'Password not matchng')
            return redirect('register')

    else:
        return render(request, 'user_signup.html')


def login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        user = auth.authenticate(username=email,password=password)

        if user is not None:
            auth.login(request, user)
            if User.objects.filter(username=email, is_superuser="True").exists():
                messages.info(request,'Admin page')
                return render(request, 'owner/owhome.html')
            else:
                # auth.login(request, user)
                return redirect("/")

        else:
            messages.info(request,'Invalied Login')
            return redirect('login')

    else:
        return render(request, 'login.html')


def logout(request):
    auth.logout(request)
    return redirect('/')

def index(request):
    return render(request, 'index.html')

def explore(request):
    return render(request, 'explore.html')

def home(request):
    return render(request, 'userHome.html')

def hotel(request):
    return render(request, 'hotel_login.html')

def hotel_signup(request):
    return render(request, 'hotelSignup.html')

def HotelAdmin(request):
    return render(request, 'hotel_Admin.html')


class hotel_list(View):
    def get(self, request):
        return render(request, 'hotel_list.html')


class city(View):
    def get(self, request):
        return render(request, 'City.html')


class booking(View):
    def get(self, request):
        return render(request, 'booking.html')    

def room_mag(request):
    return render(request, 'room_mag.html')

class room_details(View):
    def get(self, request):
        return render(request, 'hotel/room-details.html')  

def data(request):
    return render(request, 'data.html')

accounts/accounts/templates/City.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title></title>
  </head>
  <body>
        
        <div class="container">
                <h1>City List</h1>
                <a class="btn btn-primary " href="{% url 'user:hoteladmin' %}"> Back </a>
            <table class="table">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>City name</th>
                    </tr>
                </thead>
                <tbody>
                   
                    <tr>
                        <th scope="row">1 </th>
                        <td>pala</td>
                    </tr>
                </tbody>
        
            </table>
             
        </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

accounts/accounts/templates/booking.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title></title>
  </head>
  <body>
    <h1>Bookings</h1>
<div class="container">
    <table class="table">
        <thead>
                <a class="btn btn-primary " href="{% url 'user:hoteladmin' %}"> Back </a>
            
            <tr>
                <th>No</th>
                <th>Hotel name</th>
                <th>Hotel address</th>
                <th>Location</th>
                <th>phone_No</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1 </th>
                <td>Samann Grand</td>
                <td>Roashanee Magu, 23000 Male City, Maldives </td>
                <td>23000 Male City</td>
                <td>9497585624</td>
                
            </tr>
            
        </tbody>

    </table>
</div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

accounts/accounts/templates/data.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title></title>
  </head>
  <body>
        
        <div class="container">
                <h1> Tables</h1>
                <a class="btn btn-primary " href="{% url 'user:hoteladmin' %}"> Back </a>
            <table class="table">
                <thead>
                    <tr>
                        
                        <th>No</th>
                        <th>Table</th>
                        <th>Download</th>
                    </tr>
                </thead>
                <tbody>
                   
                    <tr>
                        <th scope="row">1 </th>
                        <td>booking</td>
                        <td><a href=""><button type="button" class="btn btn-success">Download</button></td></a>
                    </tr>
                </tbody>
        
            </table>
             
        </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

accounts/accounts/templates/hotelSignup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/dist/assets/css/styles.css">
    <title>ADITI | HOTEL SIGN-UP</title>
</head>
<body>
    <div class="homeSec">
        <a href="/dist/templates/index.html"><img src="/dist/assets/images/home.svg" alt="" class="home"></a>
    </div>
    <div class="cardH">
        <h1 class="header">Create Account</h1>
        

        <form action="">
            <div class="container">

                <hr>
                <div class="name">
                    <input type="text" name="fname" id="fname" placeholder="Hotel Name">
                    <input type="text" name="lname" id="lname" placeholder="Location">
                </div>
                <input type="email" name="email" id="email" placeholder="Email"><br>
                <input type="email" name="cemail" id="c_email" placeholder="Re-enter E-mail"><br>
                <input type="tel" name="phone" id="phn" placeholder="ZIP Code"><br>
                <input type="password" name="pass" id="pass" placeholder="Password"><br>
                <input type="password" name="cpass" id="c_pass" placeholder="Confirm Password">

                <hr>

                <button type="submit" class="registerbtn">Register</button>
            </div>

            <div class="container signin">
                <p>Already have an account? <a href="{% url 'user:hotel_login' %}">Sign in</a>.</p>
            </div>
        </form>
    </div>
</body>
</html>

accounts/accounts/templates/hotel_Admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles_admin.css' %}">
    <title>ADMIN | HOME</title>
</head>
<body>
    <input type="checkbox" id="check">
    <label for="check">
        <img src="{% static 'image/menu.svg' %}" alt="" class="helpers" id="btn">
        <img src="{% static 'image/cancel.svg' %}" alt="" class="helpers" id="cancel">
    </label>
    <div class="sidebar">
        <header>ADITI</header>
        <ul>
            <li><a href="{% url 'user:booking' %}"><img src="{% static 'image/calendar.svg' %}" alt="" class="icons">Booking Management</a></li>
            <li><a href="{% url 'user:room_management' %}"><img src="{% static 'image/open-door.svg' %}" alt="" class="icons">Room Management</a></li>
            <li><a href="{% url 'user:data' %}"><img src="{% static 'image/report.svg' %}" alt="" class="icons">Report Analytics</a></li>
            <li><a href="{% url 'user:hotel_list' %}"><img src="{% static 'image/clipboard.svg' %}" alt="" class="icons">Hotel List</a></li>
            <li><a href="#"><img src="{% static 'image/payment-method.svg' %}" alt="" class="icons">Payout</a></li>
            <li><a href="#"><img src="{% static 'image/mobile-payment.svg' %}" alt="" class="icons">Payment</a></li>
        </ul>
    </div>
    <section>
        
    </section>
</body>
</html>

accounts/accounts/templates/hotel_list.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title></title>
  </head>
  <body>
    <h1>hotels</h1>
<div class="container">
    <table class="table">
        <thead>
                <a class="btn btn-primary " href="{% url 'user:hoteladmin' %}"> Back </a>
            
            <tr>
                <th>No</th>
                <th>Hotel name</th>
                <th>Hotel address</th>
                <th>Location</th>
                <th>phone_No</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1 </th>
                <td>Samann Grand</td>
                <td>Roashanee Magu, 23000 Male City, Maldives </td>
                <td>23000 Male City</td>
                <td>9497585624</td>
                
            </tr>
            
        </tbody>

    </table>
</div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

accounts/accounts/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>ADITI || HOME</title>
</head>
<header class="header">
    <a href="#"><img src="{% static 'image/home.svg' %}" alt="" class="home"></a>
    <!-- Smaller Screen search -->
    <div class="header--right">
        <img src="{% static 'image/loupe.svg' %}" alt="">
        <input type="text" name=""  class="search">
        <div class="qr"></div>
    </div>
</header>

<body>
    <!-- Head Section -->
    <div class="header__section">
        <div></div>
        <div class="header__section--right">
            <img src="{% static 'image/loupe.svg' %}" alt="">
            <input type="text" name=""  class="search">
            <div class="qr"></div>
        </div>
        <!-- Smaller screen actions -->
        <div class="header__section--actions">
            <img src="{% static 'image/messenger.svg' %}" alt="" class="msg">
            <input type="button" value="MESSAGE" class="mes">
            <img src="{% static 'image/user.svg' %}" alt="" class="pro">
            <input type="button" value="PROFILE" class="prof">
            <img src="{% static 'image/admin.svg' %}" alt="" class="hst">
            <a href="{% url 'user:hoteladmin' %}"><input type="button" value="I'M A HOST" class="host"></a>
        </div>
    </div>
    <!-- Main Section -->
    <div class="main__section">
        <div class="main__section--core">
            <a href="{% url 'user:explore' %}" class="exp"><input type="button" value="Explore" class="explore"></a>
            <a href="{% url 'user:u_home' %}" class="jmp"><input type="button" value="ADITHI" class="jump"></a>
            <img src="{% static 'image/pin.svg' %}" class="pin">
        </div>
        <div class="main__section--actions">
            <img src="{% static 'image/messenger.svg' %}" alt="" class="msg">
            <input type="button" value="MESSAGE" class="mes"><br>
            <img src="{% static 'image/user.svg' %}" alt="" class="pro">
            <input type="button" value="PROFILE" class="prof"><br>
            <img src="{% static 'image/admin.svg' %}" alt="" class="hst">
            <a href="{% url 'user:hoteladmin' %}"><input type="button" value="I'M A HOST" class="host"></a>
        </div>
    </div>
    <!-- Ad Section -->
    <div class="ad__section">
        <img src="{% static 'image/hotel.jpg' %}" alt="" class="htl">
        <img src="{% static 'image/resort.jpg' %}" alt="" class="rst">
        <img src="{% static 'image/homestay.jpg' %}" alt="" class="hmsty">
        <img src="{% static 'image/unique.jpg' %}" alt="" class="unq">
        <img src="{% static 'image/dormet.jpg' %}" alt="" class="drm">
        <img src="{% static 'image/farnhouse.jpg' %}" alt="" class="frmh">
        <img src="{% static 'image/rental.jpg' %}" alt="" class="rntrms">
    </div>

    <!-- Feature Section -->
    <div class="ft__section">
        <img src="{% static 'image/hotel.jpg' %}" alt="" class="htl">
        <img src="{% static 'image/resort.jpg' %}" alt="" class="rst">
        <img src="{% static 'image/homestay.jpg' %}" alt="" class="hmsty">
        <img src="{% static 'image/unique.jpg' %}" alt="" class="unq">
        <img src="{% static 'image/dormet.jpg' %}" alt="" class="drm">
        <img src="{% static 'image/farnhouse.jpg' %}" alt="" class="frmh">
        <img src="{% static 'image/rental.jpg' %}" alt="" class="rntrms">
    </div>
</body>

</html>

accounts/accounts/templates/userHome.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ADITI || USER-HOME</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<header class="user_header">
    <div></div>
    <div class="header__right-authSection">
        <img src="{% static 'image/user.svg' %}" alt="" class="pro_img">
        <div class="btn_group">
            <a href="{% url 'user:login' %}"><button class="btn_border">Login</button></a>
            <a href="{% url 'user:register' %}"><button>Sign Up</button></a>
        </div>
    </div>
</header>

<div class="master__options">

    <div class="options">
        <select name="cars" id="location">
            <option disabled selected>Choose Location</option>
            <option value="">Addu City</option>
            <option value="">Dhidhdhoo</option>
            <option value="">Kulhudhuffushi</option>
            <option value="">Eydhafushi</option>
            <option value="">Farukolhufunadhoo</option>
            <option value="">Felidhoo</option>
            <option value="">Funadhoo</option>
            <option value="">Fuvahmulah</option>
            <option value="">Gan</option>
            <option value="">Hinnavaru</option>
            <option value="">Hithadhoo</option>
            <option value="">Hulhumalé</option>
            <option value="">Hulhumeedhoo</option>
            <option value="">Kudahuvadhoo</option>
            <option value="">Magoodhoo</option>
            <option value="">Mahibadhoo</option>
            <option value="">Malé</option>
            <option value="">Manadhoo</option>
            <option value="">Maroshi</option>
            <option value="">Meedhoo</option>
            <option value="">Mula</option>
            <option value="">Naifaru</option>
            <option value="">Nolhivaranfaru</option>
            <option value="">Thinadhoo</option>
            <option value="">Ungoofaaru</option>
            <option value="">Veymandhoo</option>
            <option value="">Veymandoo</option>
            <option value="">Viligili</option>

        </select>
        <!-- <select name="cars" id="checkin">
            <option disabled selected>Check-In</option>
            <option value="volvo">Volvo</option>
            <option value="saab">Saab</option>
            <option value="opel">Opel</option>
            <option value="audi">Audi</option>
        </select> -->
        <input type="date" name="checkin" id="checkin" placeholder="Check-In">
        <!-- <select name="cars" id="checkout">
            <option disabled selected>Check-Out</option>
            <option value="volvo">Volvo</option>
            <option value="saab">Saab</option>
            <option value="opel">Opel</option>
            <option value="audi">Audi</option>
        </select> -->
        <input type="date" name="checkout" id="checkout" placeholder="Check-Out">
        <select name="cars" id="rooms">
            <option disabled selected>Rooms</option>
            <option value="">Single</options>
            <option value="">Double</options>
            <option value="">Triple</options>
            <option value="">Quad</options>
            <option value="">Queen</options>
            <option value="">King</options>
            <option value="">Twin</options>
            <option value="">Double-double</options>
            <option value="">Studio</options>
        </select>
        <select name="cars" id="adults">
            <option disabled selected>Adults</option>
            <option value="">1</option>
            <option value="">2</option>
            <option value="">3</option>
            <option value="">4</option>
            <option value="">5</option>
            <option value="">6</option>
            <option value="">7</option>
            <option value="">8</option>
            <option value="">9</option>
            <option value="">10</option>
        </select>
        <select name="cars" id="children">
            <option disabled selected>Children</option>
            <option value="">1</option>
            <option value="">2</option>
            <option value="">3</option>
            <option value="">4</option>
            <option value="">5</option>
            <option value="">More than 5</option>
        </select>
        <button class="search">SEARCH</button>
    </div>
</div>

<body>
    <div class="hero__container">
        <div class="wrapper">
            <div class="display-tiles">
                <div class="content">
                    <div class="item">
                        <strong class="alert">PREMIUM</strong><br>
                        <strong>HOTELS</strong>
                    </div>
                    <div class="subContent">
                        <h6>TAILOR-MADE <br> FOR YOU</h6>
                    </div>
                    <button class="explore">
                        EXPLORE NOW
                    </button>
                </div>
                <img src="{% static 'image/tile1.jpg' %}" alt="">
            </div>
            <div class="display-tiles">
                <div class="content">
                    <div class="item">
                        <strong>ROOMS <br> FOR</strong>
                        <strong class="alert">TWO</strong>
                    </div>
                    <div class="subContent">
                        <h6>SPEND GREAT <br> TIME TOGETHER</h6>
                    </div>
                    <button class="explore">
                        EXPLORE NOW
                    </button>
                </div>
                <img src="{% static 'image/tile1.jpg' %}" alt="">
            </div>
            <div class="offer-tiles">
                <h1>
                    80
                    <span>
                        <div><small>%</small></div>
                    </span>
                    <span>
                        <div><small>off</small></div>
                    </span>
                </h1>
            </div>
        </div>
    </div>

    <div class="content__holder">
        <div class="content-heading">
            <h3>POPULAR CITIES IN MALDIVES</h3>
        </div>
        <div class="city_tiles">
            <div class="block">
                <h1 class="header-text">BAA TOLL</h1>
                <img src="{% static 'image/tile1.jpg' %}" alt="">
            </div>
            <div class="block">
                <h1 class="header-text">DHIGURAH</h1>
                <img src="{% static 'image/tile1.jpg' %}" alt="">
            </div>
            <div class="block lb">
                <h1 class="header-text">THULUSDHOO</h1>
                <img src="{% static 'image/tile1.jpg' %}" alt="">
            </div>
        </div>
    </div>

    <div class="content__holder2">
        <div class="content-heading2">
            <h3>BROWSE BY PROPERTY TYPE</h3>
        </div>
        <div class="city_tiles2">
            <div class="block2">
                <h1 class="header-text2">BAA TOLL</h1>
                <img src="{% static 'image/tile1.jpg' %}" alt="">
            </div>
            <div class="block2">
                <h1 class="header-text2">DHIGURAH</h1>
                <img src="{% static 'image/tile1.jpg' %}" alt="">
            </div>
            <div class="block2 lb2">
                <h1 class="header-text2">THULUSDHOO</h1>
                <img src="{% static 'image/tile1.jpg' %}" alt="">
            </div>
        </div>
    </div>

</body>

</html>